<a href="https://colab.research.google.com/github/kashishkumar2005/MLLab/blob/main/ML_LAB_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Write a program to create a numpy array using a python list . Display the array and print the shape and datatype of the array .



In [ ]:
import numpy as np
lst = [10, 20, 30, 40, 50]
arr = np.array(lst)

print("Array:", arr)
print("Shape:", arr.shape)
print("Data type:", arr.dtype)


Array: [10 20 30 40 50]
Shape: (5,)
Data type: int64


Write a program to create 3X3 matrix of 0s , create 2X5 matrix of 1s . print both matrices and their shape.

In [ ]:
import numpy as np

zeros_matrix = np.zeros((3, 3))
ones_matrix = np.ones((2, 5))

print("3x3 Zero Matrix:\n", zeros_matrix)
print("Shape:", zeros_matrix.shape)

print("\n2x5 Ones Matrix:\n", ones_matrix)
print("Shape:", ones_matrix.shape)


3x3 Zero Matrix:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Shape: (3, 3)

2x5 Ones Matrix:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Shape: (2, 5)


Write a program to create a Numpy array of numbers from 1 to 12. Reshape the array into a 3X4 matrix. Display the original and reshape array along with their shapes.

In [ ]:
import numpy as np

arr = np.arange(1, 13)
reshaped_arr = arr.reshape(3, 4)

print("Original Array:", arr)
print("Original Shape:", arr.shape)

print("\nReshaped Array:\n", reshaped_arr)
print("Reshaped Shape:", reshaped_arr.shape)


Original Array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Original Shape: (12,)

Reshaped Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Reshaped Shape: (3, 4)


Write a program to create Numpy array of 10 random integers . Find min , max , mean and sum of elements of the arrays.

In [ ]:
import numpy as np

arr = np.random.randint(1, 100, 10)

print("Array:", arr)
print("Minimum:", arr.min())
print("Maximum:", arr.max())
print("Mean:", arr.mean())
print("Sum:", arr.sum())


Array: [18 26 96 18 62 69 82 76 17 50]
Minimum: 17
Maximum: 96
Mean: 51.4
Sum: 514


Write a program to create a dataframe using a dictionary containing student name and marks.Display the dataframe and print the datatype of each column.

In [ ]:
import pandas as pd

data = {
    "Student_Name": ["Aman", "Pooja", "Riya", "Karan"],
    "Marks": [85, 92, 78, 88]
}
df = pd.DataFrame(data)

print("DataFrame:\n", df)
print("\nData Types:\n", df.dtypes)


DataFrame:
   Student_Name  Marks
0         Aman     85
1        Pooja     92
2         Riya     78
3        Karan     88

Data Types:
 Student_Name    object
Marks            int64
dtype: object


Write a program to read a csv file. Display the first 5 records and last 5 records.

In [ ]:
import pandas as pd

df = pd.read_csv("DataState.csv")

print("First 5 Records:\n", df.head())
print("\nLast 5 Records:\n", df.tail())


First 5 Records:
           States/UTs  \
0     Andhra Pradesh   
1  Arunachal Pradesh   
2              Assam   
3              Bihar   
4       Chhattisgarh   

   Total Number of Persons Injured in Road Accidents on State Highways during 2019  \
0                                            24619.0                                 
1                                              309.0                                 
2                                             7473.0                                 
3                                             7206.0                                 
4                                            13090.0                                 

   Total Number of Persons Injured in Road Accidents on State Highways during 2020  \
0                                            19675.0                                 
1                                              185.0                                 
2                                             5269.0          

Write a program to load a dataset and display the no of rows , columns and missing values

In [ ]:
import pandas as pd

df = pd.read_csv("DataState.csv")

print("Number of Rows:", df.shape[0])
print("Number of Columns:", df.shape[1])

print("\nMissing Values in Each Column:\n", df.isnull().sum())


Number of Rows: 38
Number of Columns: 6

Missing Values in Each Column:
 States/UTs                                                                         0
Total Number of Persons Injured in Road Accidents on State Highways during 2019    1
Total Number of Persons Injured in Road Accidents on State Highways during 2020    2
Total Number of Persons Injured in Road Accidents on State Highways during 2021    1
Total Number of Persons Injured in Road Accidents on State Highways during 2022    1
Total Number of Persons Injured in Road Accidents on State Highways during 2023    1
dtype: int64


Write a program to read a csv file into a data frame and display the statistical summary using describe method. Interpret mean, standard deviation, min and max values

In [ ]:
import pandas as pd

df = pd.read_csv("DataState.csv")

print("Statistical Summary using describe():\n")
print(df.describe())

print("\nMean of each numerical column:\n")
print(df.mean(numeric_only=True))

print("\nStandard Deviation of each numerical column:\n")
print(df.std(numeric_only=True))

print("\nMinimum value of each numerical column:\n")
print(df.min(numeric_only=True))

print("\nMaximum value of each numerical column:\n")
print(df.max(numeric_only=True))


Statistical Summary using describe():

       Total Number of Persons Injured in Road Accidents on State Highways during 2019  \
count                                          37.000000                                 
mean                                        24289.729730                                 
std                                         73758.319054                                 
min                                             1.000000                                 
25%                                           318.000000                                 
50%                                          5152.000000                                 
75%                                         21999.000000                                 
max                                        449360.000000                                 

       Total Number of Persons Injured in Road Accidents on State Highways during 2020  \
count                                          36.000000    